config/routes.rb
Rails.application.routes.draw do
  
    resources :events
    resources :photos
    resources :stories

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :photos
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :event
  belongs_to :story

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/models/story.rb
class Story < ActiveRecord::Base
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :set_event, only: [:show, :edit, :delete, :update ]

  def index
  	@events = Event.all
  end

  def show
    @photos =@event.photos
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      
      params[:images]
      params[:images].each do |image|
        @event.photos.create(image: image)
    end

      @photos = @event.photos
      redirect_to edit_event_path(@event), notice: "Saved..."
    else 
      render :new
    end
  end

  def edit
    # if current_user.id == @event.user.id
      @photos = @event.photos
  end

  def destroy
  	set_event #Why have to put set_event?
    @event.destroy

    flash.notice = "Event '#{@event.title}' has been deleted!"
    redirect_to events_path
  end

  def update		
    set_event																																			
  	if @event.update(event_params)

      if params[:images]
        params[:images].each do |image|
          @event.photos.create(image: image)
        end
      end

      redirect_to event_path(@event), notice: "Updated...."
    else
      render :edit
    end 
  end

  private
	  def set_event
	  	@event = Event.find(params[:id])
	  end

	  def event_params
	    params.require(:event).permit(:organization_id, :title, :description, :date_type, :start_date, 
        :end_date, :address, :city, :state, :country, :num_of_volunteer, :dateline, :requirements, :animals,
        :sports, :arts_and_culture, :technology, :education, :children_and_youth, :community, :environment, 
        :homeless_and_housing, :women, :seniors, :disaster_relief, :health, :immigratnts_refugees, :special_events )
	  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  def destroy
  	@photo = Photo.find(params[:id])
  	event = @photo.event

  	@photo.destroy
  	@photos = Photo.where(event_id: event.id)

  	respond_to :js

  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :delete, :update ]

  def index
    @stories = Story.all
  end

  def new
    @story = Story.new
  end

  def show
    @photos =@story.photos
  end

  def create
    @story = Story.new(story_params)
    if @story.save
      
      params[:images]
      params[:images].each do |image|
        @story.photos.create(image: image)
    end

      @photos = @story.photos
      redirect_to edit_story_path(@story), notice: "Saved..."
    else 
      render :new
    end
  end

  def edit
    # if current_user.id == @event.user.id
      @photos = @story.photos
  end

  def destroy
  	set_story #Why have to put set_event?
    @story.destroy

    flash.notice = "Story '#{@story.title}' has been deleted!"
    redirect_to stories_path
  end

  def update		
    set_story																																			
  	if @story.update(story_params)

      if params[:images]
        params[:images].each do |image|
          @story.photos.create(image: image)
        end
      end

      redirect_to story_path(@story), notice: "Updated...."
    else
      render :edit
    end 
  end

  private
    def set_story
	  @story = Story.find(params[:id])
	end

	def story_params
	  params.require(:story).permit(:user_id, :title, :body )
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for @event, html: {multipart: true} do |f| %>
  <ul>
    <% @event.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
    <p>
      <%= f.label :Title %><br />
      <%= f.text_field :title %>
    </p>
    <p>DATE
      <%= f.radio_button :date_type, 'True', :name => "data_type", :value => "True" %> Specific
      <%= f.radio_button :date_type, 'False',:name => "data_type", :value => "False", :checked => "checked" %> Flexible <br>
      <div id="sspecific" >
      Start Date: <%= f.text_field :start_date, :id=>"start_date" %>
      End Date: <%= f.text_field :end_date, :id=>"end_date" %>
      </div>
    </p>
    <p>
       <%= f.label :Description %>
       <%= f.text_area :description %>
    </p>

    <h1><strong>Location</strong></h1>

    <p>
      <%= f.label :Address %><br />
      <%= f.text_field :address %>
    </p>
    <p>
      <%= f.label :City %><br />
      <%= f.text_field :city %>
    </p>
    <p>
      <%= f.label :State %><br />
      <%= f.text_field :state %>
    </p>
    <p>
      <%= f.label :Country %><br />
      <%= f.text_field :country %>
    </p>

    <h1><strong>What causes does your event relate to?</strong></h1>

    <p><%= f.label :"Arts and Culture" %>
        <%= f.check_box :arts_and_culture %><br>
        <%= f.label :Sports %>
        <%= f.check_box :sports %><br>
        <%= f.label :Animals %>
        <%= f.check_box :animals %><br>
        <%= f.label :Technology %>
        <%= f.check_box :technology %><br>
        <%= f.label :Education %>
        <%= f.check_box :education %><br>
        <%= f.label :"Children and Youth" %>
        <%= f.check_box :children_and_youth %><br>
        <%= f.label :Community %>
        <%= f.check_box :community %><br>
        <%= f.label :Environment %>
        <%= f.check_box :environment %><br>
        <%= f.label :"Homeless and Housing" %>
        <%= f.check_box :homeless_and_housing %><br>
        <%= f.label :Women %>
        <%= f.check_box :women %><br>
        <%= f.label :Seniors %>
        <%= f.check_box :seniors %><br>
        <%= f.label :"Disaster Relief" %>
        <%= f.check_box :disaster_relief %><br>
        <%= f.label :Health %>
        <%= f.check_box :health %><br>
        <%= f.label :"Immigrants/Refugees" %>
        <%= f.check_box :immigrants_refugees %><br>
        <%= f.label :"Special Events" %>
        <%= f.check_box :special_events %></p>

    <h1><strong>Volunteer Info</strong></h1>
    
    <p>
      <%= f.label :Number_of_Volunteers %><br />
      <%= f.text_field :num_of_volunteer %>
    </p>
    <p>
      Deadline: <%= f.text_field :dateline, :id=>"deadline" %>
    </p>
    <p>
      <%= f.label :Requirements %><br />
      <%= f.text_field :requirements %>
    </p>
    
    <h1><strong>Pictures</strong></h1>
    <i class = "fa fa-cloud-upload fa-lg"></i> Upload Photos for event
    <%= file_field_tag "images[]", type: :file, multiple: true %>

    <div id="photos"><%= render 'photos/list' %></div>
    
    <p>
      <%= f.submit :COMPLETE %>
    </p>
    
<% end %>



<script>
  $(document).ready(function(){

    $("#sspecific").hide();

    $("input:radio[name='data_type']").change(function(){  

            if(this.value == 'True' && this.checked){
              $("#sspecific").show();
            }
            else{
              $("#sspecific").hide();
            }

    });

});

  $(function(){

    $('#start_date').datepicker({
      dateFormat: 'dd-mm-yy'
    });

    $('#end_date').datepicker({
      dateFormat: 'dd-mm-yy'
    });

    $('#deadline').datepicker({
      dateFormat: 'dd-mm-yy'
    });


   });


</script>

app/views/events/edit.html.erb
<h1> Edit an Event </h1>

<%= render partial: 'form' %>

<%= button_to "Go to Event List", event_path(@event), :method => :get %>

app/views/events/index.html.erb
<h1> All Upcoming Events </h1>

<ul id="events">
  <div id="photos"><%= render 'photos/list' %></div>
  <% @events.each do |event| %>
    <li>
      <%= image_tag event.photos[0].image.url(:thumb) %><br>
      <strong><%= link_to event.title, event_path(event) %></strong><br>
      <%= event.city %> <%= event.state %> <br><br>
      <p>Requirement:</p>
      <%= event.requirements %>
    </li>
  <% end %>
</ul>

<%= link_to "Create a New Event", new_event_path, class: "new_event" %>

app/views/events/new.html.erb
<h1> Create a New Event </h1>

<%= render partial: 'form' %>

app/views/events/show.html.erb
<div id="photos"><%= render 'photos/list' %></div>

<h1><strong> @organization.name </strong></h1>
<h2> @organization.location, @organization.state </h2>

<p><strong> We care about </strong></p>
<h3> @organization.categories(From organization) </h3>

<%=link_to "EDIT EVENT", edit_event_path(@event) %>
<%= link_to "DELETE EVENT", @event, method: :delete %>

<p><strong>This event categories:</strong></p>
				<% if @event.animals %>
					Animals, 
				<% end %> 
				<% if @event.arts_and_culture %>
					Arts and Culture, 
				<% end %> 
				<% if @event.children_and_youth %>
					Children and Youth, 
				<% end %> 
				<% if @event.community %>
					Community, 
				<% end %> 
				<% if @event.disaster_relief %>
					Disaster Relief, 
				<% end %> 
				<% if @event.education %>
					Education, 
				<% end %> 
				<% if @event.environment %>
					Environment, 
				<% end %> 
				<% if @event.health %>
					Health, 
				<% end %> 
				<% if @event.homeless_and_housing %>
					Homeless And Housing, 
				<% end %> 
				<% if @event.immigrants_refugees %>
					Immigrants And Refugees, 
				<% end %> 
				<% if @event.seniors %>
					Seniors, 
				<% end %> 
				<% if @event.sports %>
					Sports, 
				<% end %>
				<% if @event.technology %>
					Technology, 
				<% end %>
				<% if @event.women %>
					Women, 
				<% end %>
				<br>

<h1><%= @event.num_of_volunteer %></h1>
<p>More Volunteers Needed</p>

<h1> 40 (How) </h1>
<p> Days to Event </p>



<h1>Event Title:<%= @event.title %></h1>
<p>Event Description:<%= @event.description %></p>
<p>Event Start Date:<%= @event.start_date %></p>
<p>Event End Date:<%= @event.end_date %></p>

<p> @Event.categories(How)</p>

<h1> Volunteer Info </h1>
<p>Event Requirement:<%= @event.requirements %></p>
<p>Signup before <%= @event.dateline %>
<p><%= link_to "Sign up as volunteer", event_path(@event) %>(Which route?)</p>

<h1>Location</h1>
<p> @Event address:<%= @event.address %>, city:<%= @event.city %>, State:<%= @event.state %>, Country:<%= @event.country %>.</p>

<p> THE Google MAP(How) </p>

<div id="map"></div>

<style>
  #map {
  	width: 100%;
  	height: 400px;
  }
</style>

<script src="http://maps.googleapis.com/maps/api/js"></script>
<script>
  function initialize() {
  	var mapCanvas = document.getElementById('map');
    var mapOptions = {
    	center: new google.maps.LatLng(<%= @event.latitude %>, <%= @event.longitude %>),
    	zoom: 14,
    	mapTypeId: google.maps.MapTypeId.ROADMAP
    }
    var map = new google.maps.Map(mapCanvas, mapOptions)

    var marker = new google.maps.Marker({
    	position: new google.maps.LatLng(<%= @event.latitude %>, <%= @event.longitude %>),
    	title: "VENUE"
    });

    marker.setMap(map);
  }
  google.maps.event.addDomListener(window, 'load', initialize);
  </script>

<h1>What Volunteers have to say </h1>

<p> @user.comment(from user) </p>

<p> LEAVE A Comment(from user) </p>

<p><%= link_to "Sign up as volunteer", event_path(@event) %></p>

<p>Temporary Back link:<%= link_to "Back", events_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Volunteer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="flash"><%= flash.notice %></p>
<%= yield %>

</body>
</html>

app/views/photos/_list.html.erb
<% if @photos %>

 <div class="row">
   <% @photos.each do |photo| %>
   <%= image_tag photo.image.url() %>
 </div>
 <%= link_to photo, remote: true, method: :delete, data: {confirm: "Are you sure?"} do %>
   <i class="fa fa-times fa-lg"></i>
 <% end %>
 <% end %>
 <% end %>

app/views/photos/destroy.js.erb
$("#photos").html("<%= j render 'photos/list' %>")

app/views/stories/edit.html.erb
<h1> Edit an Story </h1>


<%= form_for @story, html: {multipart: true} do |f| %>
  <ul>
    <% @story.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
    <p>
      <%= f.label :Title %><br />
      <%= f.text_field :title %>
    </p>

     <p>
      <%= f.label :Body %><br />
      <%= f.text_area :body %>
    </p>
  
 
  <h1><strong>Pictures</strong></h1>
    <i class = "fa fa-cloud-upload fa-lg"></i> Upload Photos for story
    <%= file_field_tag "images[]", type: :file, multiple: true %>

    <div id="photos"><%= render 'photos/list' %></div>
    
  <p>
    <%= f.submit :PUBLISH %>
  </p>
  <% end %>

<%= button_to "Go to Story List", story_path(@story), :method => :get %>

app/views/stories/index.html.erb
<h1> All Stories </h1>

<ul id="stories">
  <p>Load Photo </p>
  <% @stories.each do |story| %>
    <li>

      <strong><%= link_to story.title, story_path(story) %> </strong><br>
      <%= story.body %>
    </li>
  <% end %>
</ul>

<%= link_to "Create a New Story", new_story_path, class: "new_story" %>

app/views/stories/new.html.erb
<h1> Write a New Experience </h1>

<%= form_for @story, html: {multipart: true} do |f| %>
  <ul>
    <% @story.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
    <p>
      <%= f.label :Title %><br />
      <%= f.text_field :title %>
    </p>

     <p>
      <%= f.label :Body %><br />
      <%= f.text_area :body %>
    </p>
  
 
  <h1><strong>Pictures</strong></h1>
    <i class = "fa fa-cloud-upload fa-lg"></i> Upload Photos for story
    <%= file_field_tag "images[]", type: :file, multiple: true %>

    <div id="photos"><%= render 'photos/list' %></div>
    
  <p>
    <%= f.submit :PUBLISH %>
  </p>

  <% end %>

app/views/stories/show.html.erb
<img src=<%= @photos %> style="width:100px;height:100px;">